### ISSUE TITLE
No such host is known

### ISSUE THREAD

**Issue by antoniogatti** [anevjes/AzureSearch.SharePointOnline#1]
**Thanks for your great work publishing this connector.**

I just finished to configure everything and I'm not able to run it fully for the first time due to this error, I really don't understand to which host is referring to. Configuration is for full crawl.

Can you give me a direction?

```
**Exception Details:**
System.Net.Http.HttpRequestException
  HResult=0x80004005
  Message=No such host is known
  Source=Microsoft.Rest.ClientRuntime
  StackTrace:
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__62.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Search.DataSourcesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Search.DataSourcesOperationsExtensions.<CreateOrUpdateAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AzureSearch.SharePointOnline.Connector.Helpers.SearchServiceHelper.<CreateOrUpdateBlobDataSourceAsync>d__2.MoveNext() in C:\code\AzureSearch.SharePointOnline-master\AzureSearch.SharepointOnline.Connector\Helpers\SearchServiceHelper.cs:line 30

Inner Exception 1:
SocketException: No such host is known
```
```
**Console Output**
..
Fetching items from drive [Documents]
located file https://MYHOST.sharepoint.com/sites/MYSITE/_layouts/15/Doc.aspx?sourcedoc=%7B6177B755-7362-443E-92AA-736DE24730EF%7D&file=Project%20One.docx&action=default&mobileredirect=true, full url [https://MYHOST.sharepoint.com/sites/MYSITE/_layouts/15/download.aspx?UniqueId=6177b755-7362-443e-92aa-736de24730ef&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvem9sdGl2YS5zaGFyZXBvaW50LmNvbUBmMGIyZjU3OS0yZjA5LTRkYWYtODM5Zi1hYmY0OWIwZDhkY2MiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNTg5NDYwMjI1IiwiZXhwIjoiMTU4OTQ2MzgyNSIsImVuZHBvaW50dXJsIjoibzkxNm5xQm9GeStVcHIxQVBXZHJXcEpIaWFNdHh2eDFoV1gyVVdoeHovWT0iLCJlbmRwb2ludHVybExlbmd0aCI6IjEzNiIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiWWpZNE5USmlORFV0TjJRNU15MDBZbUZpTFdJMlkyTXRZak15WWpRNU56TmlObUU0IiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6Ill6STFOVFE0WVdZdE4yRmhOaTAwWW1Ka0xUZzRNalF0WVdFMU16SmxOV014WXpJMCIsImFwcF9kaXNwbGF5bmFtZSI6IkF6dXJlU2VhcmNoLlNoYXJlUG9pbnRPbmxpbmUuQ3Jhd2xlciIsIm5hbWVpZCI6ImEyOTgzNjE5LWYwODctNGIzYy1hNTkyLTZiNmUwOGQwNDAzZkBmMGIyZjU3OS0yZjA5LTRkYWYtODM5Zi1hYmY0OWIwZDhkY2MiLCJyb2xlcyI6Imdyb3VwLnJlYWQgYWxsc2l0ZXMucmVhZCIsInR0IjoiMSIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGx9.ZVBXdUU4RUxMYWwyQndOeUxROEs0VG9YbVYzaWZVR2R0TVR6ZW5YeGtDMD0&ApiVersion=2.0]
file https://MYHOST.sharepoint.com/sites/MYSITE/_layouts/15/Doc.aspx?sourcedoc=%7B6177B755-7362-443E-92AA-736DE24730EF%7D&file=Project%20One.docx&action=default&mobileredirect=true.json written to Azure BLOB
file https://MTHOST.sharepoint.com/sites/MYSITE/_layouts/15/Doc.aspx?sourcedoc=%7B6177B755-7362-443E-92AA-736DE24730EF%7D&file=Project%20One.docx&action=default&mobileredirect=true written to Azure BLOB
Creating 'blob-datasource' blob data source...
```

![image](https://user-images.githubusercontent.com/11330675/81936243-8609ce00-9624-11ea-8c16-2db8adc8ec85.png)

**Comment by antoniogatti** [comment]
I found the issue, just a typo in the search service name in the configuration
```
 "SearchDetails": {
      "name": "myservice-search",
```
